// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // We only support web for Yorked MVP
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQJmTALoHjXc9ZC-vorvDOtgF-HIixoXM',
    appId: '1:496198857009:web:4a6ab09834a9ae77c40010',
    messagingSenderId: '496198857009',
    projectId: 'yorked-e06e3',
    authDomain: 'yorked-e06e3.firebaseapp.com',
    storageBucket: 'yorked-e06e3.firebasestorage.app',
    measurementId: 'G-J011FNQQDF',
  );
}
